_wandb:
    value:
        cli_version: 0.19.0
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 9
                - 41
                - 55
                - 103
            "2":
                - 1
                - 9
                - 41
                - 55
                - 103
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.7
            "5": 0.19.0
            "8":
                - 3
                - 5
            "12": 0.19.0
            "13": windows-amd64
batch_size:
    value: 8
epochs:
    value: 10
experiment_name:
    value: intra-modal-consistency-loss-v1
learning_rate:
    value: 0.001
run_name:
    value: intra-modal-consistency-loss-v1-079d7829
