_wandb:
    value:
        cli_version: 0.19.0
        m: []
        python_version: 3.10.10
        t:
            "1":
                - 1
                - 9
                - 41
                - 55
            "2":
                - 1
                - 9
                - 41
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.10
            "5": 0.19.0
            "8":
                - 5
            "12": 0.19.0
            "13": linux-x86_64
batch_size:
    value: 2
epochs:
    value: 2
experiment_name:
    value: intra-modal-consistency-loss-v1
learning_rate:
    value: 0.001
run_name:
    value: intra-modal-consistency-loss-v1-b90235fa
