_wandb:
    value:
        cli_version: 0.19.0
        m: []
        python_version: 3.9.5
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 9
                - 41
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.9.5
            "5": 0.19.0
            "8":
                - 5
            "12": 0.19.0
            "13": linux-x86_64
batch_size:
    value: 2
d_model:
    value: 512
dim_feedforward:
    value: 2048
epochs:
    value: 10
experiment_name:
    value: multimodal-feature-extractor-v1
learning_rate:
    value: 0.0001
nhead:
    value: 8
num_encoder_layers:
    value: 6
run_name:
    value: multimodal-feature-extractor-v1-8e34c66a
